---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore 
summary: Astra可從快照或備份還原應用程式組態和持續儲存設備。持續儲存備份會從物件存放區傳輸、因此從現有備份還原將能最快完成。 
---
= 還原應用程式
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control Center可從快照或備份還原應用程式。持續儲存備份與快照會從物件存放區傳輸、因此從現有快照還原至同一個叢集的速度將比其他方法更快。您可以使用Astra UI或 https://docs.netapp.com/us-en/astra-automation-2108/index.html["Astra API"^] 以還原應用程式。


NOTE: 如果您使用Helm來部署應用程式、Astra Control Center需要Helm版本3。完全支援使用Helm 3部署的應用程式管理與複製（或從Helm 2升級至Helm 3）。不支援以Helm 2部署的應用程式。


NOTE: 如果還原至不同的叢集、請確定叢集使用相同的持續磁碟區存取模式（例如ReadWriteMany）。如果目的地持續磁碟區存取模式不同、還原作業將會失敗。

[NOTE]
====
當您在OpenShift叢集上建立裝載應用程式的專案時、專案（或Kubernetes命名空間）會被指派安全性轉換唯一碼。若要啟用Astra Control Center來保護應用程式、並將應用程式移至OpenShift中的其他叢集或專案、您必須新增原則、讓應用程式以任何唯一識別碼的形式執行。例如、下列OpenShift CLI命令會將適當的原則授予WordPress應用程式。

「occ new－project worm新聞」（occ new－project wormPress）「ocadm policy add－scc to－group anyuid system:serviceaccounts：wormPress」（ocadm policy add－scc對使用者權限-z預設值-n wormPress）

====
.步驟
. 按一下*應用程式*、然後按一下應用程式名稱。
. 按一下*資料保護*。
. 如果要從快照還原、請選取* Snapshot*圖示。否則、按一下*備份*圖示即可從備份還原。
. 按一下「*動作*」欄中的下拉式清單、以取得您要還原的快照或備份。
. 按一下*還原應用程式*。
. *還原詳細資料*：指定還原的詳細資料：
+
** 輸入應用程式的名稱和命名空間。
+

NOTE: 如果您要還原已刪除的應用程式、請為應用程式選擇不同於原始名稱的名稱和命名空間。如果還原的應用程式名稱與刪除的應用程式相同、還原作業將會失敗。

** 選擇應用程式的目的地叢集。
** 按一下* Review *。


. *還原摘要*：檢閱還原動作的詳細資料、然後按一下*還原*。


Astra Control Center會根據您提供的資訊來還原應用程式。


NOTE: 資料保護作業（複製、備份、還原）及後續持續調整磁碟區大小之後、UI中會顯示新的磁碟區大小、延遲最多20分鐘。資料保護作業只需幾分鐘就能成功完成、您可以使用儲存後端的管理軟體來確認磁碟區大小的變更。
