---
sidebar: sidebar 
permalink: get-started/add-cluster-reqs.html 
keywords: what are astra prerequisites, what is Astra Control, add kubernetes cluster, astra trident version 
summary: 您應該執行易用性檢查、以確保叢集已準備好新增至Astra控制中心。 
---
= 新增叢集的必要條件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


在新增叢集之前、您應確保符合先決條件。您也應該執行資格檢查、以確保叢集已準備好新增至Astra控制中心。



== 新增叢集之前所需的功能

* 執行OpenShift 4.6或4.7的叢集、其Trident StorageClass以ONTAP 支援功能為後盾、可支援使用支援版本號為9、5或更新版本。
+
** 一或多個工作節點、至少有1GB RAM可供執行遙測服務。
+

NOTE: 如果您打算將第二個OpenShift 4.6或4.7叢集新增為受管理的運算資源、則應確保已啟用Trident Volume Snapshot功能。請參閱官方Trident https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/operations/tasks/volumes/snapshots.html?highlight=volumesnapshot#on-demand-volume-snapshots["說明"^] 以Trident啟用及測試Volume Snapshot。



* 支援ONTAP 的支援功能不只是超級使用者和使用者ID、更能使用Astra Control Center（Acc）來備份和還原應用程式。在ONTAP 支援指令行中執行下列命令：「匯出原則規則修改-vserver svm0 -policyname預設-rueindex 1 -root進 階使用者sys」「匯出原則規則修改-policyname預設-rueindex 1 -anon 65534」（這是預設值）




== 執行資格檢查

執行下列資格檢查、確保您的叢集已準備好新增至Astra控制中心。

.步驟
. 檢查Trident版本。
+
[listing]
----
kubectl get tridentversions -n trident
----
+
如果存在Trident、您會看到類似下列的輸出：

+
[listing]
----
NAME      VERSION
trident   21.04.0
----
+
如果Trident不存在、您會看到類似下列的輸出：

+
[listing]
----
error: the server doesn't have a resource type "tridentversions"
----
+

NOTE: 如果未安裝Trident或安裝的版本不是最新版本、您必須先安裝最新版本的Trident、才能繼續進行。請參閱 https://netapp-trident.readthedocs.io/en/latest/kubernetes/deploying/deploying.html#deploying-in-kubernetes["Trident文件"^] 以取得相關指示。

. 檢查儲存類別是否使用支援的Trident驅動程式。置備程式名稱應為「csi.trident.netapp.io`」。請參閱下列範例：
+
[listing]
----
kubectl get storageClass -A
NAME                   PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ontap-gold (default)   csi.trident.netapp.io          Delete          Immediate           true                   5d23h
thin                   kubernetes.io/vsphere-volume   Delete          Immediate           false                  6d
----




== 建立管理角色KECBEConfig

在執行步驟之前、請先確定機器上有下列項目：

* 安裝了「kubecll」v1.19或更新版本
* 具有作用中內容叢集管理權限的作用中Kbeconfig


.步驟
. 建立服務帳戶、如下所示：
+
.. 建立名為「astracontinal-service-account.yaml」的服務帳戶檔案。
+
視需要調整名稱和命名空間。如果在此處進行變更、您應該在下列步驟中套用相同的變更。

+
[source, subs="specialcharacters,quotes"]
----
*astracontrol-service-account.yaml*
----
+
[listing]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: astracontrol-service-account
  namespace: default
----
.. 套用服務帳戶：
+
[listing]
----
kubectl apply -f astracontrol-service-account.yaml
----


. 授予叢集管理權限、如下所示：
+
.. 建立名為「astracontletil-clusterrolebind.yaml」的「ClusterRoeBinding」檔案。
+
視需要在建立服務帳戶時調整任何已修改的名稱和命名空間。

+
[source, subs="specialcharacters,quotes"]
----
*astracontrol-clusterrolebinding.yaml*
----
+
[listing]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: astracontrol-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: astracontrol-service-account
  namespace: default
----
.. 套用叢集角色繫結：
+
[listing]
----
kubectl apply -f astracontrol-clusterrolebinding.yaml
----


. 列出服務帳戶機密、將「<內容>」取代為正確的安裝內容：
+
[listing]
----
kubectl get serviceaccount astracontrol-service-account --context <context> --namespace default -o json
----
+
輸出的結尾應類似於下列內容：

+
[listing]
----
"secrets": [
{ "name": "astracontrol-service-account-dockercfg-vhz87"},
{ "name": "astracontrol-service-account-token-r59kr"}
]
----
+
"secretts "陣列中每個元素的索引以0開頭。在上述範例中、「astracontlivter-service-account-dockercfg-vhz87」的索引為0、而「astracontlive-service-account-toke-r59kr"的索引則為1。在輸出中、記下含有「權杖」一詞的服務帳戶名稱索引。

. 產生以下的Kbeconfig：
+
.. 建立「cree-kupeconfig．sh」檔案。如果您在上一步中記下的權杖索引不是0、請將下列指令碼開頭的「toke_index」值改為正確的值。
+
[source, subs="specialcharacters,quotes"]
----
*create-kubeconfig.sh*
----
+
[listing]
----
# Update these to match your environment. Replace the value for TOKEN_INDEX from
# the output in the previous step if it was not 0. If you didn't change anything
# else above, don't change anything else here.

SERVICE_ACCOUNT_NAME=astracontrol-service-account
NAMESPACE=default
NEW_CONTEXT=astracontrol
KUBECONFIG_FILE='kubeconfig-sa'
TOKEN_INDEX=0

CONTEXT=$(kubectl config current-context)

SECRET_NAME=$(kubectl get serviceaccount ${SERVICE_ACCOUNT_NAME} \
  --context ${CONTEXT} \
  --namespace ${NAMESPACE} \
  -o jsonpath='{.secrets[TOKEN_INDEX].name}')
TOKEN_DATA=$(kubectl get secret ${SECRET_NAME} \
  --context ${CONTEXT} \
  --namespace ${NAMESPACE} \
  -o jsonpath='{.data.token}')

TOKEN=$(echo ${TOKEN_DATA} | base64 -d)

# Create dedicated kubeconfig
# Create a full copy
kubectl config view --raw > ${KUBECONFIG_FILE}.full.tmp

# Switch working context to correct context
kubectl --kubeconfig ${KUBECONFIG_FILE}.full.tmp config use-context ${CONTEXT}

# Minify
kubectl --kubeconfig ${KUBECONFIG_FILE}.full.tmp \
  config view --flatten --minify > ${KUBECONFIG_FILE}.tmp

# Rename context
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  rename-context ${CONTEXT} ${NEW_CONTEXT}

# Create token user
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-credentials ${CONTEXT}-${NAMESPACE}-token-user \
  --token ${TOKEN}

# Set context to use token user
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-context ${NEW_CONTEXT} --user ${CONTEXT}-${NAMESPACE}-token-user

# Set context to correct namespace
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-context ${NEW_CONTEXT} --namespace ${NAMESPACE}

# Flatten/minify kubeconfig
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  view --flatten --minify > ${KUBECONFIG_FILE}

# Remove tmp
rm ${KUBECONFIG_FILE}.full.tmp
rm ${KUBECONFIG_FILE}.tmp
----
.. 請輸入命令以將其套用至Kubernetes叢集。
+
[listing]
----
source create-kubeconfig.sh
----


. （*選用*）將KUbeconfig重新命名為有意義的叢集名稱。保護您的叢集認證資料。
+
[listing]
----
chmod 700 create-kubeconfig.sh
mv kubeconfig-sa.txt YOUR_CLUSTER_NAME_kubeconfig
----




== 接下來呢？

現在您已經確認已符合先決條件、您已經準備好了 link:setup_overview.html["新增叢集"^]。

[discrete]
== 如需詳細資訊、請參閱

* https://netapp-trident.readthedocs.io/en/latest/frequently_asked_questions.html["Trident文件"^]
* https://docs.netapp.com/us-en/astra-automation-2108/index.html["使用Astra API"^]

