---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 已知問題可識別可能導致您無法成功使用本產品版本的問題。 
---
= 此版本的已知問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


已知問題可識別可能導致您無法成功使用本產品版本的問題。

下列已知問題會影響目前的版本：

* <<由Astra Control Center CRD在安裝期間建立的Cluster角色 繫結不正確>>
* <<具有使用者定義標籤的應用程式會進入「移除」狀態>>
* <<無法停止執行應用程式備份>>
* <<在Astra Control Center中使用具有十進位單位的PVCS來備份或複製應用程式時失敗>>
* <<Astra Control Center UI會緩慢顯示應用程式資源的變更、例如持續變更磁碟區>>
* <<從備份Trident還原應用程式時、會建立比原始PV更大的PV>>
* <<大型持續磁碟區會影響複製效能>>
* <<使用特定版本的PostgreSQL時、應用程式複製失敗>>
* <<使用服務帳戶層級OCP安全內容限制（SCC）時、應用程式複製失敗>>
* <<Astra Control Center中的S3鏟斗未報告可用容量>>
* <<重複使用Astra Control Center執行個體之間的儲存區會導致故障>>
* <<選取具有其他類型認證的庫位供應商類型會導致資料保護失敗>>
* <<在移除Astra Control Center執行個體期間、可能無法保留備份與快照>>
* <<額外備份會保留為排程備份的一部分>>
* link:known-issues.html#clone-operation-cant-use-other-buckets-besides-the-default["除了預設值、Clone作業無法使用其他儲存區"]
* <<使用Astra Control Center管理叢集失敗、因為預設的Kbeconfig檔案包含多個內容>>
* link:known-issues.html#cant-determine-asup-tar-bundle-status-in-scaled-environment["無法判斷擴充環境中的ASUP tar套件狀態"]
* <<解除安裝Astra Control Center無法清除受管理叢集上的監控操作員Pod>>
* <<解除安裝Astra Control Center無法清除Traefik CRD>>
* <<ASUP收藏卡在產生或上傳狀態>>




== 由Astra Control Center CRD在安裝期間建立的Cluster角色 繫結不正確

將下列修補程式套用至所有已部署acc營運者版本21.08.65的Kubernetes叢集。如果重新部署了acc操作員、也應套用此功能。

若要解決此問題：

. 將下方指令碼中的「ACC_命名 空間」取代為您先前使用的命名空間 link:../get-started/install_acc.html#install-astra-control-center["部署Astra控制中心"]。
+
[source, cli]
----
cat <<EOF | kubectl apply -f –
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acc-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acc-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: netapp-acc-operator
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:ACC_NAMESPACE
EOF
----
. 執行指令碼。


此修補程式會從「ClusterRoeBinding：ACC-oper-manager-roleBinding」（叢集角色繫結）中移除下列兩個主題

[listing]
----
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
- apiGroup: ""
  kind: Group
  name: system:serviceaccounts
----


== 具有使用者定義標籤的應用程式會進入「移除」狀態

如果您使用不存在的k8s標籤定義應用程式、Astra Control Center將會建立、管理應用程式、然後立即移除應用程式。若要避免這種情況、請在Astra Control Center管理應用程式之後、將k8s標籤新增至Pod和資源。



== 無法停止執行應用程式備份

無法停止執行中的備份。如果您需要刪除備份、請等到備份完成後再使用中的指示 link:../use/protect-apps.html#delete-backups["刪除備份"]。若要刪除失敗的備份、請使用 link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["Astra API"^]。



== 在Astra Control Center中使用具有十進位單位的PVCS來備份或複製應用程式時失敗

使用Astra Control Center備份或複製程序建立的小數位磁碟區失敗。請參閱 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Backup_or_clone_may_fail_for_applications_using_PVCs_with_decimal_units_in_Astra_Control_Center["知識庫文章"] 以取得更多資訊。



== Astra Control Center UI會緩慢顯示應用程式資源的變更、例如持續變更磁碟區

資料保護作業（複製、備份、還原）及後續持續調整磁碟區大小之後、UI中會顯示新的磁碟區大小、延遲最多20分鐘。新增或修改任何應用程式資源時、也會發生UI延遲。在這種情況下、資料保護作業只需幾分鐘就能成功完成、您可以使用儲存後端的管理軟體來確認磁碟區大小的變更。



== 從備份Trident還原應用程式時、會建立比原始PV更大的PV

如果您在建立備份之後調整持續磁碟區的大小、然後從該備份還原、則持續磁碟區大小會與PV的新大小相符、而非使用備份的大小。



== 大型持續磁碟區會影響複製效能

非常大且耗用的持續磁碟區複本可能會間歇性緩慢、這取決於叢集對物件存放區的存取。如果該實體複本已掛起、且超過30分鐘未複製任何資料、Astra Control會終止該實體複製動作。



== 使用特定版本的PostgreSQL時、應用程式複製失敗

同一個叢集內的應用程式複製作業、會持續失敗、並顯示Bitnami PostgreSQL 11.5.0圖表。若要成功複製、請使用舊版或更新版本的圖表。



== 使用服務帳戶層級OCP安全內容限制（SCC）時、應用程式複製失敗

如果在OCP叢集的命名空間中、於服務帳戶層級設定原始的安全性內容限制、則應用程式複製可能會失敗。當應用程式複製失敗時、它會出現在Astra Control Center的「託管應用程式」區域、狀態為「移除」。請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Application_clone_is_failing_for_an_application_in_Astra_Control_Center["知識庫文章"] 以取得更多資訊。



== Astra Control Center中的S3鏟斗未報告可用容量

在備份或複製由Astra Control Center管理的應用程式之前、請先查看ONTAP 資訊庫（英文）或StorageGRID 資訊庫（英文）管理系統中的庫位資訊。



== 重複使用Astra Control Center執行個體之間的儲存區會導致故障

如果您嘗試重複使用另一個或先前安裝Astra Control Center所使用的儲存區、備份與還原將會失敗。您必須使用不同的鏟斗、或是完全清除先前使用過的鏟斗。您無法在Astra Control Center的執行個體之間共用儲存區。



== 選取具有其他類型認證的庫位供應商類型會導致資料保護失敗

新增儲存庫時、請使用該供應商適用的認證資料、選取正確的儲存庫供應商類型。例如、UI接受NetApp ONTAP S3作為StorageGRID 具備支援功能的認證類型、但這會導致所有未來使用此儲存庫的應用程式備份與還原作業失敗。



== 在移除Astra Control Center執行個體期間、可能無法保留備份與快照

如果您擁有評估授權、請務必儲存您的帳戶ID、以免在Astra Control Center故障時發生資料遺失（如果您未傳送ASUP）。



== 額外備份會保留為排程備份的一部分

有時Astra Control Center中的一或多個備份會保留超過備份排程中指定的保留數量。這些額外的備份應作為排程備份的一部分刪除、但不會刪除、而且會陷入「擱置中」狀態。若要解決此問題、 https://docs.netapp.com/us-en/astra-automation-2108/workflows/wf_delete_backup.html["強制刪除"] 額外備份：



== 除了預設值、Clone作業無法使用其他儲存區

在應用程式備份或應用程式還原期間、您可以選擇性地指定庫位ID。不過、應用程式複製作業一律會使用已定義的預設儲存區。沒有選項可變更實體複本的儲存區。如果您想要控制所使用的儲存桶、您也可以選擇 link:../use/manage-buckets.html#edit-a-bucket["變更庫位預設值"] 或執行 link:../use/protect-apps.html#create-a-backup["備份"] 接著是A link:../use/restore-apps.html["還原"] 獨立提供。



== 使用Astra Control Center管理叢集失敗、因為預設的Kbeconfig檔案包含多個內容

您無法在其中使用多個叢集和內容的Kbeconfig。請參閱 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["知識庫文章"] 以取得更多資訊。



== 無法判斷擴充環境中的ASUP tar套件狀態

在ASUP採樣期間、UI中的套裝組合狀態會報告為「collection」（正在收集）或「done」（單一）。大型環境最多需要一小時的收集時間。ASUP下載期間、套裝組合的網路檔案傳輸速度可能不足、而且下載可能會在15分鐘後逾時、UI中並無任何指示。下載問題取決於ASUP的大小、擴充的叢集大小、以及收集時間是否超過七天限制。



== 解除安裝Astra Control Center無法清除受管理叢集上的監控操作員Pod

如果在卸載Astra Control Center之前未取消管理叢集、您可以使用下列命令手動刪除NetApp監控命名空間和命名空間中的Pod：

.步驟
. 刪除「acc監控」代理程式：
+
[listing]
----
oc delete agents acc-monitoring -n netapp-monitoring
----
+
結果：

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. 刪除命名空間：
+
[listing]
----
oc delete ns netapp-monitoring
----
+
結果：

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. 確認移除的資源：
+
[listing]
----
oc get pods -n netapp-monitoring
----
+
結果：

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. 確認監控代理程式已移除：
+
[listing]
----
oc get crd|grep agent
----
+
結果範例：

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. 刪除自訂資源定義（CRD）資訊：
+
[listing]
----
oc delete crds agents.monitoring.netapp.com
----
+
結果：

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




== 解除安裝Astra Control Center無法清除Traefik CRD

您可以手動刪除Traefik客戶需求日：

.步驟
. 確認解除安裝程序未刪除哪些客戶需求日：
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
回應

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. 刪除客戶需求日：
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us
----




== ASUP收藏卡在產生或上傳狀態

如果ASUP Pod被中止或重新啟動、則ASUP集合可能會陷入產生或上傳狀態。請執行下列步驟 link:https://docs.netapp.com/us-en/astra-automation-2108/index.html["Astra Control REST API"] 再次致電以啟動手動收集：

[cols="25,75"]
|===
| HTTP方法 | 路徑 


| 貼文 | /Accounts/｛AccountID｝/core / v1/asups 
|===

NOTE: 此API因應措施僅適用於在ASUP啟動後10分鐘以上的情況。



== 如需詳細資訊、請參閱

* link:../release-notes/known-limitations.html["此版本的已知限制"]

